Repository QuivrHQ/quivr, pull requests merged in 2024-12, with the labels that each got.

#3493 feat: first version (V0) of the Workflow Management System
  core/quivr_core/llm_tools/web_search_tools.py
  core/quivr_core/rag/entities/config.py
  core/quivr_core/rag/prompts.py
  core/quivr_core/rag/quivr_rag_langgraph.py
Labels: lgtm, size:L

#3514 fix: dealing with empty tool_calls
  core/quivr_core/rag/utils.py
Labels: lgtm, size:S

#3510 chore(main): release core 0.0.26
  .release-please-manifest.json
  core/CHANGELOG.md
  core/pyproject.toml
Labels: autorelease: pending, autorelease: tagged, size:S

#3519 feat: ensuring that max_context_tokens is never larger than what supported by models
  core/quivr_core/rag/entities/config.py
Labels: lgtm, size:L

#3521 feat: send all to megaparse_sdk
  core/pyproject.toml
  core/quivr_core/processor/implementations/megaparse_processor.py
  core/quivr_core/processor/registry.py
Labels: lgtm, size:S

#3525 fix: fixing errors arising when the user input contains no tasks
  core/quivr_core/rag/quivr_rag_langgraph.py
Labels: lgtm, size:XS

#3520 chore(main): release core 0.0.27
  .release-please-manifest.json
  core/CHANGELOG.md
  core/pyproject.toml
Labels: autorelease: pending, autorelease: tagged, size:S

#3526 feat: remove dependencies on Pydantic v1
  core/pyproject.toml
  core/quivr_core/llm/llm_endpoint.py
  core/quivr_core/llm_tools/web_search_tools.py
  core/quivr_core/rag/entities/models.py
  core/requirements-dev.lock
  core/requirements.lock
  core/tests/test_llm_endpoint.py
  docs/docs/brain/chat.md
  docs/docs/config/config.md
  docs/pyproject.toml
  docs/requirements-dev.lock
  docs/requirements.lock
  examples/chatbot/requirements-dev.lock
  examples/chatbot/requirements.lock
  examples/chatbot_voice/requirements-dev.lock
  examples/chatbot_voice/requirements.lock
  examples/quivr-whisper/pyproject.toml
  examples/quivr-whisper/requirements-dev.lock
  examples/quivr-whisper/requirements.lock
  examples/simple_question/requirements-dev.lock
  examples/simple_question/requirements.lock
  requirements-dev.lock
  requirements.lock
Labels: lgtm, size:M

#3527 chore(main): release core 0.0.28
  .release-please-manifest.json
  core/CHANGELOG.md
  core/pyproject.toml
Labels: autorelease: pending, autorelease: tagged, size:S

#3528 feat: improving the prompts to always refer to 'tasks' instead of 'questions'
  core/quivr_core/rag/prompts.py
  core/quivr_core/rag/quivr_rag_langgraph.py
Labels: lgtm, size:M

#3530 feat: langfuse integration
  core/pyproject.toml
  core/quivr_core/rag/quivr_rag_langgraph.py
  core/requirements-dev.lock
  core/requirements.lock
Labels: size:XS

#3532 feat: language detection after chunking
  core/pyproject.toml
  core/quivr_core/brain/brain.py
  core/quivr_core/language/models.py
  core/quivr_core/language/utils.py
  core/quivr_core/processor/processor_base.py
  core/requirements-dev.lock
  core/requirements.lock
Labels: lgtm, size:L

#3533 feat: langfuse user id
  core/quivr_core/brain/brain.py
Labels: size:S

#3539 feat: returning a description of each workflow node
  core/quivr_core/rag/entities/config.py
  core/quivr_core/rag/entities/models.py
  core/quivr_core/rag/quivr_rag_langgraph.py
Labels: lgtm, size:S
