Repository QuivrHQ/quivr, pull requests merged in 2024-11, with the labels that each got.

#3446 feat: kms-migration
  core/quivr_core/files/file.py
  core/quivr_core/processor/implementations/megaparse_processor.py
  core/quivr_core/processor/implementations/tika_processor.py
  core/quivr_core/processor/processor_base.py
  core/quivr_core/processor/registry.py
  core/quivr_core/rag/entities/models.py
  core/quivr_core/rag/quivr_rag_langgraph.py
Labels: size:M

#3462 feat(megaparse): add sdk
  core/pyproject.toml
  core/quivr_core/config.py
  core/quivr_core/processor/implementations/megaparse_processor.py
  core/quivr_core/processor/registry.py
  core/tests/processor/pdf/test_megaparse_pdf_processor.py
  examples/simple_question_megaparse.py
Labels: lgtm, size:L

#3466 fix: added chunk_size in tika processor
  core/quivr_core/processor/implementations/tika_processor.py
Labels: lgtm, size:XS

#3476 Fix/add_megaparse_lib_
  core/pyproject.toml
  core/quivr_core/processor/implementations/megaparse_processor.py
Labels: lgtm, size:M

#3447 chore(main): release core 0.0.24
  .release-please-manifest.json
  core/CHANGELOG.md
  core/pyproject.toml
Labels: autorelease: pending, autorelease: tagged, size:S

#3487 feat(example): chatbot UI
  examples/chatbot/.chainlit/config.toml
  examples/chatbot/.gitignore
  examples/chatbot/main.py
  examples/chatbot/public/favicon.ico
  examples/chatbot/public/logo_dark.png
  examples/chatbot/public/logo_light.png
  examples/chatbot/requirements-dev.lock
  examples/chatbot/requirements.lock
Labels: lgtm, size:M

#3489 chore(examples): add basic RAG workflow configuration
  examples/chatbot/basic_rag_workflow.yaml
  examples/chatbot/main.py
Labels: size:M

#3490 chore(chatbot): update Quivr assistant UI configuration
  examples/chatbot/.chainlit/config.toml
Labels: area: frontend, size:XS

#3491 feat(example): chatbot voice
  examples/chatbot_voice/.chainlit/config.toml
  examples/chatbot_voice/.chainlit/translations/bn.json
  examples/chatbot_voice/.chainlit/translations/en-US.json
  examples/chatbot_voice/.chainlit/translations/gu.json
  examples/chatbot_voice/.chainlit/translations/he-IL.json
  examples/chatbot_voice/.chainlit/translations/hi.json
  examples/chatbot_voice/.chainlit/translations/kn.json
  examples/chatbot_voice/.chainlit/translations/ml.json
  examples/chatbot_voice/.chainlit/translations/mr.json
  examples/chatbot_voice/.chainlit/translations/ta.json
  examples/chatbot_voice/.chainlit/translations/te.json
  examples/chatbot_voice/.chainlit/translations/zh-CN.json
  examples/chatbot_voice/.gitignore
  examples/chatbot_voice/.python-version
  examples/chatbot_voice/README.md
  examples/chatbot_voice/basic_rag_workflow.yaml
  examples/chatbot_voice/chainlit.md
  examples/chatbot_voice/main.py
  examples/chatbot_voice/public/favicon.ico
  examples/chatbot_voice/public/logo_dark.png
  examples/chatbot_voice/public/logo_light.png
  examples/chatbot_voice/pyproject.toml
  examples/chatbot_voice/requirements-dev.lock
  examples/chatbot_voice/requirements.lock
Labels: size:XXL

#3492 feat(quivr-whisper): add initial project files
  examples/quivr-whisper/.env_example
  examples/quivr-whisper/.gitignore
  examples/quivr-whisper/.python-version
  examples/quivr-whisper/README.md
  examples/quivr-whisper/Readme.md
  examples/quivr-whisper/app.py
  examples/quivr-whisper/pyproject.toml
  examples/quivr-whisper/requirements-dev.lock
  examples/quivr-whisper/requirements.lock
  examples/quivr-whisper/static/app.js
  examples/quivr-whisper/static/styles.css
  examples/quivr-whisper/templates/index.html
Labels: size:L

#3494 fix: two small fixes
  docs/docs/workflows/examples/rag_with_web_search.md
  examples/chatbot/basic_rag_workflow.yaml
  examples/quivr-whisper/README.md
  examples/quivr-whisper/Readme.md
Labels: size:L

#3496 fix: megaparse sdk with nats
  core/pyproject.toml
  core/quivr_core/processor/implementations/megaparse_processor.py
  examples/simple_question_megaparse.py
Labels: lgtm, size:M

#3495 feat(example): Quivr whisper
  .vscode/settings.json
  examples/quivr-whisper/.gitignore
  examples/quivr-whisper/app.py
  examples/quivr-whisper/pyproject.toml
  examples/quivr-whisper/requirements-dev.lock
  examples/quivr-whisper/requirements.lock
  examples/quivr-whisper/static/app.js
  examples/quivr-whisper/static/loader.svg
  examples/quivr-whisper/static/mic-off.svg
  examples/quivr-whisper/static/mic.svg
  examples/quivr-whisper/static/styles.css
  examples/quivr-whisper/templates/index.html
Labels: lgtm, size:XL

#3506 docs: Enhance example/chatbot with added instructions
  core/quivr_core/rag/entities/config.py
  examples/chatbot/README.md
Labels: lgtm, size:S

#3502 docs(Examples): Add documentation for chatbot, chatbot_voice and quivr-whisper examples
  docs/docs/examples/assets/chatbot_voice_flask.mp4
  docs/docs/examples/chatbot.md
  docs/docs/examples/chatbot_voice.md
  docs/docs/examples/chatbot_voice_flask.md
  docs/mkdocs.yml
  docs/requirements-dev.lock
  docs/requirements.lock
Labels: size:L

#3500 chore(main): release core 0.0.25
  .release-please-manifest.json
  core/CHANGELOG.md
  core/pyproject.toml
Labels: autorelease: pending, autorelease: tagged, size:S
