Repository QuivrHQ/quivr, pull requests merged in 2025-02, with the labels that each got.

#3586 add: zendesk workflow
  core/example_workflows/talk_to_file_rag_config_workflow.yaml
  core/quivr_core/rag/prompts.py
  core/quivr_core/rag/quivr_rag_langgraph.py
Labels: size:L

#3592 fix: Zendesk system prompt
  core/quivr_core/rag/prompts.py
Labels: lgtm, size:S

#3594 feat: megaparse v54
  core/.flake8
  core/pyproject.toml
  core/quivr_core/processor/implementations/default.py
  core/quivr_core/processor/implementations/megaparse_processor.py
  core/quivr_core/processor/implementations/simple_txt_processor.py
  core/quivr_core/processor/implementations/tika_processor.py
  core/quivr_core/processor/processor_base.py
Labels: lgtm, size:M
