Repository QuivrHQ/quivr, pull requests merged in 2025-03, with the labels that each got.

#3606 feat: core input metadata zendesk
  .flake8
  core/quivr_core/brain/brain.py
  core/quivr_core/rag/entities/config.py
  core/quivr_core/rag/prompts.py
  core/quivr_core/rag/quivr_rag.py
  core/quivr_core/rag/quivr_rag_langgraph.py
  core/quivr_core/rag/utils.py
Labels: size:L

#3612 feat: arbitrary additional data for zendesk
  core/quivr_core/rag/prompts.py
  core/quivr_core/rag/quivr_rag_langgraph.py
Labels: size:XS

#3613 feat: add guidelines
  core/quivr_core/rag/prompts.py
  core/quivr_core/rag/quivr_rag_langgraph.py
Labels: lgtm, size:S

#3615 feat: fix chat with model
  core/quivr_core/brain/brain.py
Labels: size:XS

#3619 feat: add zendesk llm template for reformulate
  core/quivr_core/rag/prompts.py
  core/quivr_core/rag/quivr_rag_langgraph.py
Labels: lgtm, size:M

#3621 feat: add filters
  core/quivr_core/rag/quivr_rag_langgraph.py
Labels: size:XS
