Repository QuivrHQ/quivr, pull requests merged in 2025-04, with the labels that each got.

#3622 feat: renamed system_prompt to correct naming
  core/quivr_core/rag/prompts.py
  core/quivr_core/rag/quivr_rag_langgraph.py
Labels: lgtm, size:XS

#3624 feat: enhance zendesk template with clearer guidelines and instructions
  core/quivr_core/rag/prompts.py
Labels: size:M

#3625 feat: add system_prompt parameter to Brain methods and enhance message handling in RAG pipeline
  core/quivr_core/brain/brain.py
  core/quivr_core/rag/prompts.py
  core/quivr_core/rag/quivr_rag_langgraph.py
Labels: size:L

#3626 refactor: improve assertion formatting and remove debug print statement in QuivrQARAGLangGraph
  core/quivr_core/rag/quivr_rag_langgraph.py
Labels: size:XS

#3629 feat: add run-id langfuse
  core/quivr_core/brain/brain.py
  core/quivr_core/rag/quivr_rag_langgraph.py
Labels: lgtm, size:S

#3628 fix: fix grammar and typo in zendesk prompte template
  core/quivr_core/rag/prompts.py
Labels: size:XS

#3631 fix(brain): pass missing run_id
  core/quivr_core/brain/brain.py
Labels: lgtm, size:XS

#3632 feat: Add Gemini support for language models
  core/pyproject.toml
  core/quivr_core/llm/llm_endpoint.py
  core/quivr_core/rag/entities/config.py
  core/quivr_core/rag/quivr_rag_langgraph.py
Labels: size:M

#3633 feat: add langchain-groq dependency and update LLMEndpoint to use ChatGroq
  core/pyproject.toml
  core/quivr_core/llm/llm_endpoint.py
Labels: size:XS
