Repository QuivrHQ/quivr, pull requests merged in 2025-01, with the labels that each got.

#3549 feat: enabling workflows without rewriting step
  core/quivr_core/rag/quivr_rag_langgraph.py
Labels: size:S

#3529 chore(main): release core 0.0.29
  .release-please-manifest.json
  core/CHANGELOG.md
  core/pyproject.toml
Labels: autorelease: pending, autorelease: tagged, size:S

#3555 feat: adding cache to LLMEndpoint
  core/quivr_core/llm/llm_endpoint.py
Labels: lgtm, size:S

#3556 chore(main): release core 0.0.30
  .release-please-manifest.json
  core/CHANGELOG.md
  core/pyproject.toml
Labels: autorelease: pending, autorelease: tagged, size:S

#3558 feat: cache tokenizers
  core/quivr_core/llm/llm_endpoint.py
  core/quivr_core/rag/entities/config.py
Labels: lgtm, size:L

#3576 feat: remove tokenizer load
  core/quivr_core/llm/llm_endpoint.py
Labels: size:XS

#3577 feat: limit tokenizers cache size
  core/pyproject.toml
  core/quivr_core/llm/llm_endpoint.py
  core/requirements-dev.lock
  core/requirements.lock
Labels: size:L

#3580 feat: remove pympler dependency and add better way to calculate size of tokenizer cache
  core/pyproject.toml
  core/quivr_core/llm/llm_endpoint.py
  core/requirements-dev.lock
  core/requirements.lock
Labels: lgtm, size:M

#3560 chore(main): release core 0.0.31
  .release-please-manifest.json
  core/CHANGELOG.md
  core/pyproject.toml
Labels: autorelease: pending, autorelease: tagged, size:S

#3583 feat: o3-mini
  core/pyproject.toml
  core/quivr_core/llm/llm_endpoint.py
  core/quivr_core/rag/entities/config.py
  core/requirements-dev.lock
  core/requirements.lock
Labels: size:M

#3584 chore(main): release core 0.0.32
  .release-please-manifest.json
  core/CHANGELOG.md
  core/pyproject.toml
Labels: autorelease: pending, autorelease: tagged, size:S
